### ISSUE TITLE
GO ribbon cells not triggering a table view when clicked (Alliance KANBAN-77 )

### ISSUE THREAD

**Issue by MagdalenaZZ** [geneontology/wc-ribbon#31]
https://agr-jira.atlassian.net/browse/KANBAN-77 

Please @tmushayahama can you look at this with some urgency?

**Comment by lpalbou** [comment]
Just commenting quickly to help @tmushayahama as it’s a tricky one and I remember it was on my todo list to solve, but didn’t have time. It also means there is a duplicate issue on this.

In a nutshell, it’s a refresh problem. If you notice, when you click on “compare orthologs”, it shows you all cells correctly:

![71EA6BF7-C4FF-4FA8-BBF7-8473A9D851A2](https://user-images.githubusercontent.com/24249870/148226283-61a0cf5c-d210-4853-a7b4-aba302a87c58.png)

However, and this is very brief, when you click on show only experimental annotations, it does show for a brief instant the correct ribbon:

![DEB52297-D2D3-4911-B53D-28167D09FDA1](https://user-images.githubusercontent.com/24249870/148226406-fbd12a98-c2db-43b8-b622-624984c05efb.png)

But this one rapidly gets replaced by the one before. So somewhere, there is something triggering a refresh and not taking into account the fact that “show only exp” was selected.

Hopefully, it will help to solve this one that can be tricky to understand otherwise !

**Comment by tmushayahama** [comment]
Thanks @lpalbou for the explanation, now I know where to start. I will have more questions soon when I get to it. @MagdalenaZZ I will be looking into this

**Comment by MagdalenaZZ** [comment]
Hi @tmushayahama , just checking in on the progress of this ticket, which Alliance PIs have labelled "High priority" and "URGENT"?

**Comment by kltm** [comment]
Talking to @tmushayahama , we would like to talk to a UI developer about how the ribbon is wired in, as we believe that the issue would be best fixed at that level--the interaction between the ribbon and the ribbon table (one of the two seems to not be (re)rendering).

**Comment by cmungall** [comment]
@MagdalenaZZ who is the best person in the Alliance to ask questions about the current front-end architecture so we can make progress on this?

**Comment by lpalbou** [comment]
A quick comment on that: clicking on a term triggers [this code](https://github.com/alliance-genome/agr_ui/blob/3bb02e16262fe0e983cd25358c60a3c70de81bfd/apps/main-app/src/components/geneOntologyRibbon/index.js#L165)  and more precisely [this one](https://github.com/alliance-genome/agr_ui/blob/3bb02e16262fe0e983cd25358c60a3c70de81bfd/apps/main-app/src/components/geneOntologyRibbon/index.js#L173). When a term is selected, this updates the state ([eg](https://github.com/alliance-genome/agr_ui/blob/3bb02e16262fe0e983cd25358c60a3c70de81bfd/apps/main-app/src/components/geneOntologyRibbon/index.js#L245)), which in turn triggers a render (normal REACT behavior). When the REACT render method is called, it also calls the [ribbon table render](https://github.com/alliance-genome/agr_ui/blob/3bb02e16262fe0e983cd25358c60a3c70de81bfd/apps/main-app/src/components/geneOntologyRibbon/index.js#L471). Be mindful however the ribbon table has its own attribute listeners ([eg](https://github.com/geneontology/wc-ribbon/blob/04a9110be54b4af95eef69b5596587c87def6ffe/wc-ribbon-table/src/components/ribbon-table/ribbon-table.tsx#L113)), so does the ribbon strips ([eg](https://github.com/geneontology/wc-ribbon/blob/04a9110be54b4af95eef69b5596587c87def6ffe/wc-ribbon-strips/src/components/ribbon-strips/ribbon-strips.tsx#L166)). From memory, this issue was a conflict between the AGR integration which does ask the ribbon to renders the correct table ([eg](https://github.com/alliance-genome/agr_ui/blob/3bb02e16262fe0e983cd25358c60a3c70de81bfd/apps/main-app/src/components/geneOntologyRibbon/index.js#L489)), but the ribbon getting new data also triggers its own rendering and forget to account for the "onlyExp" parameter, therefore doing a refresh with the wrong context.

To take with a grain of salt as it's from memory.

**Comment by kltm** [comment]
In discussion with @tmushayahama , there has been some progress here. Description from email thread to follow.

**Comment by tmushayahama** [comment]
Note: **This is not a wc-ribbon component issue but the agr-ui site implementation** 

The problem stems from a filter that prevents the table from rendering if the experimental codes are not included in a specific list. In this case, the codes 'IBA' and 'ALL' were not rendering.

The relevant code snippet can be found at this line: https://github.com/alliance-genome/agr_ui/blob/f094a532729a5b0ca17c28d0c8674522fbe5dfc5/apps/main-app/src/components/geneOntologyRibbon/index.js#L21

``` javascript
const EXP_CODES = ['EXP', 'IBA', 'ALL', 'IDA', 'IPI', 'IMP', 'IGI', 'IEP', 'HTP', 'HDA', 'HMP', 'HGI', 'HEP'];
```

Upon clicking the ribbon cell, it successfully retrieves the data from api with 'IBA' code. However, it is then filtered out before reaching the rendering ribbon table, resulting in the undesired behavior. We discussed whether this is a bug or intended behavior, and also whether it would be appropriate to add 'IBA' and 'ALL' to the EXP_CODES list.

Please review the filter implementation below: https://github.com/alliance-genome/agr_ui/blob/f094a532729a5b0ca17c28d0c8674522fbe5dfc5/apps/main-app/src/components/geneOntologyRibbon/index.js#L471

Tagging @kltm @cmungall

**Comment by vanaukenk** [comment]
See testing on:  https://agr-jira.atlassian.net/browse/SCRUM-2806

**Comment by kltm** [comment]
Excellent!
