### ISSUE TITLE
`wc-go-autocomplete` component only shows first letter of matched label

### ISSUE THREAD

**Issue by pkalita-lbl** [geneontology/wc-ribbon#46]
If I enter "bmp" into the `wc-go-autocomplete` search box, I get a list of results. However, the gene symbols in the results only shows one letter. This can be observed on https://geneontology.org/ribbon.

<img width="447" alt="image" src="https://github.com/user-attachments/assets/130d5b7f-3b4b-43ad-bd1b-fb29937c9073">

The code that renders the label is pulling the 0th element from the `label` field of the documents returned by the API: https://github.com/geneontology/wc-ribbon/blob/04a9110be54b4af95eef69b5596587c87def6ffe/wc-go-autocomplete/src/components/go-autocomplete/go-autocomplete.tsx#L152

I wonder if the API used to provide an array of strings in the `label` field and at some point changed to provide a single string?

**Comment by kltm** [comment]
@pgaudet @tmushayahama @dustine32 Your memories may be better than mine for this. As this was a toy demonstrator, I'm not sure this is an issue with the widget per se, or just an issue with the demo? I'm trying to figure out where this goes in the fixing priorities...

**Comment by pgaudet** [comment]
I dont remember seeing this.

**Comment by lpalbou** [comment]
Hi all, I still get some notifications on this repo, so decided to pass by. 

It was quite some time ago but the gene names were showing otherwise we would never have integrated it on the [ribbon sandbox page](https://geneontology.org/ribbon.html), so it seems something must have changed at the API level indeed. In the meantime, if you want, it's a very simple fix: https://github.com/geneontology/wc-ribbon/pull/49

**Comment by pkalita-lbl** [comment]
Fixed by https://github.com/geneontology/wc-ribbon/pull/49
